// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// DefaultClusterConfig describes the default cluster configurations to be
/// applied to all clusters born-in-fleet.
public struct DefaultClusterConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Enable/Disable Security Posture features for the cluster.
  public var securityPostureConfig: SecurityPostureConfig? = nil

  /// Optional. Enable/Disable binary authorization features for the cluster.
  public var binaryAuthorizationConfig: BinaryAuthorizationConfig? = nil

  /// Optional. Enable/Disable Compliance Posture features for the cluster.
  /// Note that on UpdateFleet, only full replacement of this field is allowed.
  /// Users are not allowed for partial updates through field mask.
  public var compliancePostureConfig: CompliancePostureConfig? = nil

  /// Initialize a new instance of `DefaultClusterConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DefaultClusterConfig().with { $0.securityPostureConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.DefaultClusterConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
