// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Feature represents the settings and status of any Fleet Feature.
public struct Feature: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The full, unique name of this Feature resource in the format
  /// `projects/*/locations/*/features/*`.
  public var name: Swift.String = Swift.String()

  /// Labels for this Feature.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. State of the Feature resource itself.
  public var resourceState: FeatureResourceState? = nil

  /// Optional. Fleet-wide Feature configuration. If this Feature does not
  /// support any Fleet-wide configuration, this field may be unused.
  public var spec: CommonFeatureSpec? = nil

  /// Optional. Membership-specific configuration for this Feature. If this
  /// Feature does not support any per-Membership configuration, this field may
  /// be unused.
  ///
  /// The keys indicate which Membership the configuration is for, in the form:
  ///
  /// `projects/{p}/locations/{l}/memberships/{m}`
  ///
  /// Where {p} is the project, {l} is a valid location and {m} is a valid
  /// Membership in this project at that location. {p} WILL match the Feature's
  /// project.
  ///
  /// {p} will always be returned as the project number, but the project ID is
  /// also accepted during input. If the same Membership is specified in the map
  /// twice (using the project ID form, and the project number form), exactly
  /// ONE of the entries will be saved, with no guarantees as to which. For this
  /// reason, it is recommended the same format be used for all entries when
  /// mutating a Feature.
  public var membershipSpecs: [Swift.String: MembershipFeatureSpec] = [:]

  /// Output only. The Fleet-wide Feature state.
  public var state: CommonFeatureState? = nil

  /// Output only. Membership-specific Feature status. If this Feature does
  /// report any per-Membership status, this field may be unused.
  ///
  /// The keys indicate which Membership the state is for, in the form:
  ///
  /// `projects/{p}/locations/{l}/memberships/{m}`
  ///
  /// Where {p} is the project number, {l} is a valid location and {m} is a valid
  /// Membership in this project at that location. {p} MUST match the Feature's
  /// project number.
  public var membershipStates: [Swift.String: MembershipFeatureState] = [:]

  /// Output only. When the Feature resource was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. When the Feature resource was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. When the Feature resource was deleted.
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Scope-specific configuration for this Feature. If this Feature
  /// does not support any per-Scope configuration, this field may be unused.
  ///
  /// The keys indicate which Scope the configuration is for, in the form:
  ///
  /// `projects/{p}/locations/global/scopes/{s}`
  ///
  /// Where {p} is the project, {s} is a valid Scope in this project.
  /// {p} WILL match the Feature's project.
  ///
  /// {p} will always be returned as the project number, but the project ID is
  /// also accepted during input. If the same Scope is specified in the map
  /// twice (using the project ID form, and the project number form), exactly
  /// ONE of the entries will be saved, with no guarantees as to which. For this
  /// reason, it is recommended the same format be used for all entries when
  /// mutating a Feature.
  public var scopeSpecs: [Swift.String: ScopeFeatureSpec] = [:]

  /// Output only. Scope-specific Feature status. If this Feature does
  /// report any per-Scope status, this field may be unused.
  ///
  /// The keys indicate which Scope the state is for, in the form:
  ///
  /// `projects/{p}/locations/global/scopes/{s}`
  ///
  /// Where {p} is the project, {s} is a valid Scope in this project.
  /// {p} WILL match the Feature's project.
  public var scopeStates: [Swift.String: ScopeFeatureState] = [:]

  /// Output only. List of locations that could not be reached while fetching
  /// this feature.
  public var unreachable: [Swift.String] = []

  /// Initialize a new instance of `Feature`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Feature().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.gkehub.v1.Feature"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
