// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Fleet contains the Fleet-wide metadata and configuration.
public struct Fleet: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The full, unique resource name of this fleet in the format of
  /// `projects/{project}/locations/{location}/fleets/{fleet}`.
  ///
  /// Each Google Cloud project can have at most one fleet resource, named
  /// "default".
  public var name: Swift.String = Swift.String()

  /// Optional. A user-assigned display name of the Fleet.
  /// When present, it must be between 4 to 30 characters.
  /// Allowed characters are: lowercase and uppercase letters, numbers,
  /// hyphen, single-quote, double-quote, space, and exclamation point.
  ///
  /// Example: `Production Fleet`
  public var displayName: Swift.String = Swift.String()

  /// Output only. When the Fleet was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. When the Fleet was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. When the Fleet was deleted.
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Google-generated UUID for this resource. This is unique across
  /// all Fleet resources. If a Fleet resource is deleted and another resource
  /// with the same name is created, it gets a different uid.
  public var uid: Swift.String = Swift.String()

  /// Output only. State of the namespace resource.
  public var state: FleetLifecycleState? = nil

  /// Optional. The default cluster configurations to apply across the fleet.
  public var defaultClusterConfig: DefaultClusterConfig? = nil

  /// Optional. Labels for this Fleet.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `Fleet`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Fleet().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.Fleet"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
