// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for `GkeHub.GenerateConnectManifest`
/// method.
/// .
public struct GenerateConnectManifestRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The Membership resource name the Agent will associate with, in
  /// the format `projects/*/locations/*/memberships/*`.
  public var name: Swift.String = Swift.String()

  /// Optional. Namespace for GKE Connect agent resources. Defaults to
  /// `gke-connect`.
  ///
  /// The Connect Agent is authorized automatically when run in the default
  /// namespace. Otherwise, explicit authorization must be granted with an
  /// additional IAM binding.
  public var namespace: Swift.String = Swift.String()

  /// Optional. URI of a proxy if connectivity from the agent to
  /// gkeconnect.googleapis.com requires the use of a proxy. Format must be in
  /// the form `http(s)://{proxy_address}`, depending on the HTTP/HTTPS protocol
  /// supported by the proxy. This will direct the connect agent's outbound
  /// traffic through a HTTP(S) proxy.
  public var proxy: Foundation.Data = Foundation.Data()

  /// Optional. The Connect agent version to use. Defaults to the most current
  /// version.
  public var version: Swift.String = Swift.String()

  /// Optional. If true, generate the resources for upgrade only. Some resources
  /// generated only for installation (e.g. secrets) will be excluded.
  public var isUpgrade: Swift.Bool = Swift.Bool()

  /// Optional. The registry to fetch the connect agent image from. Defaults to
  /// gcr.io/gkeconnect.
  public var registry: Swift.String = Swift.String()

  /// Optional. The image pull secret content for the registry, if not public.
  public var imagePullSecretContent: Foundation.Data = Foundation.Data()

  /// Initialize a new instance of `GenerateConnectManifestRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateConnectManifestRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.GenerateConnectManifestRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
