// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol GkeHubStub: Sendable {
    func listMemberships(
      request: ListMembershipsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.ListMembershipsResponse

    func listBoundMemberships(
      request: ListBoundMembershipsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.ListBoundMembershipsResponse

    func listFeatures(
      request: ListFeaturesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.ListFeaturesResponse

    func getMembership(
      request: GetMembershipRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.Membership

    func getFeature(
      request: GetFeatureRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.Feature

    func createMembership(
      request: CreateMembershipRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createFeature(
      request: CreateFeatureRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteMembership(
      request: DeleteMembershipRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteFeature(
      request: DeleteFeatureRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateMembership(
      request: UpdateMembershipRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateFeature(
      request: UpdateFeatureRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func generateConnectManifest(
      request: GenerateConnectManifestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.GenerateConnectManifestResponse

    func createFleet(
      request: CreateFleetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getFleet(
      request: GetFleetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.Fleet

    func updateFleet(
      request: UpdateFleetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteFleet(
      request: DeleteFleetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listFleets(
      request: ListFleetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.ListFleetsResponse

    func getScopeNamespace(
      request: GetScopeNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.Namespace

    func createScopeNamespace(
      request: CreateScopeNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateScopeNamespace(
      request: UpdateScopeNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteScopeNamespace(
      request: DeleteScopeNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listScopeNamespaces(
      request: ListScopeNamespacesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.ListScopeNamespacesResponse

    func getScopeRbacroleBinding(
      request: GetScopeRBACRoleBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.RBACRoleBinding

    func createScopeRbacroleBinding(
      request: CreateScopeRBACRoleBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateScopeRbacroleBinding(
      request: UpdateScopeRBACRoleBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteScopeRbacroleBinding(
      request: DeleteScopeRBACRoleBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listScopeRbacroleBindings(
      request: ListScopeRBACRoleBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.ListScopeRBACRoleBindingsResponse

    func getScope(
      request: GetScopeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.Scope

    func createScope(
      request: CreateScopeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateScope(
      request: UpdateScopeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteScope(
      request: DeleteScopeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listScopes(
      request: ListScopesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.ListScopesResponse

    func listPermittedScopes(
      request: ListPermittedScopesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.ListPermittedScopesResponse

    func getMembershipBinding(
      request: GetMembershipBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.MembershipBinding

    func createMembershipBinding(
      request: CreateMembershipBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateMembershipBinding(
      request: UpdateMembershipBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteMembershipBinding(
      request: DeleteMembershipBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listMembershipBindings(
      request: ListMembershipBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.ListMembershipBindingsResponse

    func getMembershipRbacroleBinding(
      request: GetMembershipRBACRoleBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.RBACRoleBinding

    func createMembershipRbacroleBinding(
      request: CreateMembershipRBACRoleBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateMembershipRbacroleBinding(
      request: UpdateMembershipRBACRoleBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteMembershipRbacroleBinding(
      request: DeleteMembershipRBACRoleBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listMembershipRbacroleBindings(
      request: ListMembershipRBACRoleBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.ListMembershipRBACRoleBindingsResponse

    func generateMembershipRbacroleBindingYaml(
      request: GenerateMembershipRBACRoleBindingYAMLRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEHubV1.GenerateMembershipRBACRoleBindingYAMLResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
