// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// KubernetesResource contains the YAML manifests and configuration for
/// Membership Kubernetes resources in the cluster. After CreateMembership or
/// UpdateMembership, these resources should be re-applied in the cluster.
public struct KubernetesResource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Input only. The YAML representation of the Membership CR. This field is
  /// ignored for GKE clusters where Hub can read the CR directly.
  ///
  /// Callers should provide the CR that is currently present in the cluster
  /// during CreateMembership or UpdateMembership, or leave this field empty if
  /// none exists. The CR manifest is used to validate the cluster has not been
  /// registered with another Membership.
  public var membershipCrManifest: Swift.String = Swift.String()

  /// Output only. Additional Kubernetes resources that need to be applied to the
  /// cluster after Membership creation, and after every update.
  ///
  /// This field is only populated in the Membership returned from a successful
  /// long-running operation from CreateMembership or UpdateMembership. It is not
  /// populated during normal GetMembership or ListMemberships requests. To get
  /// the resource manifest after the initial registration, the caller should
  /// make a UpdateMembership call with an empty field mask.
  public var membershipResources: [ResourceManifest] = []

  /// Output only. The Kubernetes resources for installing the GKE Connect agent
  ///
  /// This field is only populated in the Membership returned from a successful
  /// long-running operation from CreateMembership or UpdateMembership. It is not
  /// populated during normal GetMembership or ListMemberships requests. To get
  /// the resource manifest after the initial registration, the caller should
  /// make a UpdateMembership call with an empty field mask.
  public var connectResources: [ResourceManifest] = []

  /// Optional. Options for Kubernetes resource generation.
  public var resourceOptions: ResourceOptions? = nil

  /// Initialize a new instance of `KubernetesResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = KubernetesResource().with { $0.membershipCrManifest = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.KubernetesResource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
