// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudGax
import GoogleCloudWkt

/// Response message for the `GkeHub.ListMemberships` method.
public struct ListMembershipsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The list of matching Memberships.
  public var resources: [Membership] = []

  /// A token to request the next page of resources from the
  /// `ListMemberships` method. The value of an empty string means that
  /// there are no more resources to return.
  public var nextPageToken: Swift.String = Swift.String()

  /// List of locations that could not be reached while fetching this list.
  public var unreachable: [Swift.String] = []

  /// Initialize a new instance of `ListMembershipsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListMembershipsResponse().with { $0.resources = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.gkehub.v1.ListMembershipsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [Membership] {
    return self.resources
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
