// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for `GkeHub.ListMemberships` method.
public struct ListMembershipsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The parent (project and location) where the Memberships will be
  /// listed. Specified in the format `projects/*/locations/*`.
  /// `projects/*/locations/-` list memberships in all the regions.
  public var parent: Swift.String = Swift.String()

  /// Optional. When requesting a 'page' of resources, `page_size` specifies
  /// number of resources to return. If unspecified or set to 0, all resources
  /// will be returned.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. Token returned by previous call to `ListMemberships` which
  /// specifies the position in the list from where to continue listing the
  /// resources.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Lists Memberships that match the filter expression, following the
  /// syntax outlined in https://google.aip.dev/160.
  ///
  /// Examples:
  ///
  ///   - Name is `bar` in project `foo-proj` and location `global`:
  ///
  ///       name = "projects/foo-proj/locations/global/membership/bar"
  ///
  ///   - Memberships that have a label called `foo`:
  ///
  ///       labels.foo:*
  ///
  ///   - Memberships that have a label called `foo` whose value is `bar`:
  ///
  ///       labels.foo = bar
  ///
  ///   - Memberships in the CREATING state:
  ///
  ///       state = CREATING
  public var filter: Swift.String = Swift.String()

  /// Optional. One or more fields to compare and use to sort the output.
  /// See https://google.aip.dev/132#ordering.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListMembershipsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListMembershipsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.ListMembershipsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
