// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request to list Memberships bound to a Scope.
public struct ListBoundMembershipsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the Scope, in the format
  /// `projects/*/locations/global/scopes/*`, to which the Memberships are bound.
  public var scopeName: Swift.String = Swift.String()

  /// Optional. Lists Memberships that match the filter expression, following the
  /// syntax outlined in https://google.aip.dev/160. Currently, filtering
  /// can be done only based on Memberships's `name`, `labels`, `create_time`,
  /// `update_time`, and `unique_id`.
  public var filter: Swift.String = Swift.String()

  /// Optional. When requesting a 'page' of resources, `page_size` specifies
  /// number of resources to return. If unspecified or set to 0, all resources
  /// will be returned. Pagination is currently not supported; therefore, setting
  /// this field does not have any impact for now.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. Token returned by previous call to `ListBoundMemberships` which
  /// specifies the position in the list from where to continue listing the
  /// resources.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListBoundMembershipsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListBoundMembershipsRequest().with { $0.scopeName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.ListBoundMembershipsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
