// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for `GkeHub.ListFeatures` method.
public struct ListFeaturesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent (project and location) where the Features will be
  /// listed. Specified in the format `projects/*/locations/*`.
  public var parent: Swift.String = Swift.String()

  /// When requesting a 'page' of resources, `page_size` specifies number of
  /// resources to return. If unspecified or set to 0, all resources will
  /// be returned.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Token returned by previous call to `ListFeatures` which
  /// specifies the position in the list from where to continue listing the
  /// resources.
  public var pageToken: Swift.String = Swift.String()

  /// Lists Features that match the filter expression, following the syntax
  /// outlined in https://google.aip.dev/160.
  ///
  /// Examples:
  ///
  ///   - Feature with the name "servicemesh" in project "foo-proj":
  ///
  ///       name = "projects/foo-proj/locations/global/features/servicemesh"
  ///
  ///   - Features that have a label called `foo`:
  ///
  ///       labels.foo:*
  ///
  ///   - Features that have a label called `foo` whose value is `bar`:
  ///
  ///       labels.foo = bar
  public var filter: Swift.String = Swift.String()

  /// One or more fields to compare and use to sort the output.
  /// See https://google.aip.dev/132#ordering.
  public var orderBy: Swift.String = Swift.String()

  /// Optional. If set to true, the response will return partial results when
  /// some regions are unreachable and the unreachable field in Feature proto
  /// will be populated. If set to false, the request will fail when some regions
  /// are unreachable.
  public var returnPartialSuccess: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ListFeaturesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListFeaturesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.ListFeaturesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
