// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// MembershipEndpoint contains information needed to contact a Kubernetes API,
/// endpoint and any additional Kubernetes metadata.
public struct MembershipEndpoint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. GKE-specific information. Only present if this Membership is a GKE cluster.
  public var gkeCluster: GkeCluster? = nil

  /// Output only. Useful Kubernetes-specific metadata.
  public var kubernetesMetadata: KubernetesMetadata? = nil

  /// Optional. The in-cluster Kubernetes Resources that should be applied for a
  /// correctly registered cluster, in the steady state. These resources:
  ///
  ///   * Ensure that the cluster is exclusively registered to one and only one
  ///     Hub Membership.
  ///   * Propagate Workload Pool Information available in the Membership
  ///     Authority field.
  ///   * Ensure proper initial configuration of default Hub Features.
  public var kubernetesResource: KubernetesResource? = nil

  /// Output only. Whether the lifecycle of this membership is managed by a
  /// google cluster platform service.
  public var googleManaged: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `MembershipEndpoint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MembershipEndpoint().with { $0.gkeCluster = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.gkehub.v1.MembershipEndpoint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
