// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// MembershipBinding is a subresource of a Membership, representing
/// what Fleet Scopes (or other, future Fleet resources) a Membership is bound
/// to.
public struct MembershipBinding: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name for the membershipbinding itself
  /// `projects/{project}/locations/{location}/memberships/{membership}/bindings/{membershipbinding}`
  public var name: Swift.String = Swift.String()

  /// Output only. Google-generated UUID for this resource. This is unique across
  /// all membershipbinding resources. If a membershipbinding resource is deleted
  /// and another resource with the same name is created, it gets a different
  /// uid.
  public var uid: Swift.String = Swift.String()

  /// Output only. When the membership binding was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. When the membership binding was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. When the membership binding was deleted.
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. State of the membership binding resource.
  public var state: MembershipBindingLifecycleState? = nil

  /// Optional. Labels for this MembershipBinding.
  public var labels: [Swift.String: Swift.String] = [:]

  /// What type of membershipbinding this is.
  public var target: OneOf_Target? = nil

  /// Initialize a new instance of `MembershipBinding`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MembershipBinding().with { $0.scope = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case scope = "scope"
    case name = "name"
    case uid = "uid"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case deleteTime = "deleteTime"
    case state = "state"
    case labels = "labels"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.uid = try container.decode(Swift.String.self, forKey: .uid)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .deleteTime)
    self.state = try container.decodeIfPresent(MembershipBindingLifecycleState.self, forKey: .state)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)

    var target: OneOf_Target? = nil
    let targetCheckAndSet = {
      if target != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'target'"))
      }
      target = $0
    }
    if let scope = try container.decodeIfPresent(Swift.String.self, forKey: .scope) {
      try targetCheckAndSet(.scope(scope))
    }
    self.target = target
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.labels, forKey: .labels)

    if let choice = self.target {
      switch choice {
      case .scope(let value):
        try container.encode(value, forKey: .scope)
      }
    }
  }

  /// What type of membershipbinding this is.
  public enum OneOf_Target: Codable, Equatable, Sendable {
    /// A Scope resource name in the format
    /// `projects/*/locations/*/scopes/*`.
    case scope(Swift.String)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.gkehub.v1.MembershipBinding"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
