// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Membership contains information about a member cluster.
public struct Membership: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The full, unique name of this Membership resource in the
  /// format `projects/*/locations/*/memberships/{membership_id}`, set during
  /// creation.
  ///
  /// `membership_id` must be a valid RFC 1123 compliant DNS label:
  ///
  ///   1. At most 63 characters in length
  ///   2. It must consist of lower case alphanumeric characters or `-`
  ///   3. It must start and end with an alphanumeric character
  ///
  /// Which can be expressed as the regex: `[a-z0-9]([-a-z0-9]*[a-z0-9])?`,
  /// with a maximum length of 63 characters.
  public var name: Swift.String = Swift.String()

  /// Optional. Labels for this membership.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Description of this membership, limited to 63 characters.
  /// Must match the regex: `[a-zA-Z0-9][a-zA-Z0-9_\-\.\ ]*`
  ///
  /// This field is present for legacy purposes.
  public var description: Swift.String = Swift.String()

  /// Output only. State of the Membership resource.
  public var state: MembershipState? = nil

  /// Output only. When the Membership was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. When the Membership was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. When the Membership was deleted.
  public var deleteTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. An externally-generated and managed ID for this Membership. This
  /// ID may be modified after creation, but this is not recommended.
  ///
  /// The ID must match the regex: `[a-zA-Z0-9][a-zA-Z0-9_\-\.]*`
  ///
  /// If this Membership represents a Kubernetes cluster, this value should be
  /// set to the UID of the `kube-system` namespace object.
  public var externalId: Swift.String = Swift.String()

  /// Output only. For clusters using Connect, the timestamp of the most recent
  /// connection established with Google Cloud. This time is updated every
  /// several minutes, not continuously. For clusters that do not use GKE
  /// Connect, or that have never connected successfully, this field will be
  /// unset.
  public var lastConnectionTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Google-generated UUID for this resource. This is unique across
  /// all Membership resources. If a Membership resource is deleted and another
  /// resource with the same name is created, it gets a different unique_id.
  public var uniqueId: Swift.String = Swift.String()

  /// Optional. How to identify workloads from this Membership.
  /// See the documentation on Workload Identity for more details:
  /// https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
  public var authority: Authority? = nil

  /// Optional. The monitoring config information for this membership.
  public var monitoringConfig: MonitoringConfig? = nil

  /// Type of resource represented by this Membership
  public var type: OneOf_Type? = nil

  /// Initialize a new instance of `Membership`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Membership().with { $0.endpoint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case endpoint = "endpoint"
    case name = "name"
    case labels = "labels"
    case description = "description"
    case state = "state"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case deleteTime = "deleteTime"
    case externalId = "externalId"
    case lastConnectionTime = "lastConnectionTime"
    case uniqueId = "uniqueId"
    case authority = "authority"
    case monitoringConfig = "monitoringConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.state = try container.decodeIfPresent(MembershipState.self, forKey: .state)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .deleteTime)
    self.externalId = try container.decode(Swift.String.self, forKey: .externalId)
    self.lastConnectionTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .lastConnectionTime)
    self.uniqueId = try container.decode(Swift.String.self, forKey: .uniqueId)
    self.authority = try container.decodeIfPresent(Authority.self, forKey: .authority)
    self.monitoringConfig = try container.decodeIfPresent(
      MonitoringConfig.self, forKey: .monitoringConfig)

    var type: OneOf_Type? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let endpoint = try container.decodeIfPresent(MembershipEndpoint?.self, forKey: .endpoint) {
      try typeCheckAndSet(.endpoint(endpoint))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.externalId, forKey: .externalId)
    try container.encode(self.lastConnectionTime, forKey: .lastConnectionTime)
    try container.encode(self.uniqueId, forKey: .uniqueId)
    try container.encode(self.authority, forKey: .authority)
    try container.encode(self.monitoringConfig, forKey: .monitoringConfig)

    if let choice = self.type {
      switch choice {
      case .endpoint(let value):
        try container.encode(value, forKey: .endpoint)
      }
    }
  }

  /// Type of resource represented by this Membership
  public enum OneOf_Type: Codable, Equatable, Sendable {
    /// Optional. Endpoint information to reach this member.
    indirect case endpoint(MembershipEndpoint?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.Membership"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
