// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Namespace represents a namespace across the Fleet
public struct Namespace: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name for the namespace
  /// `projects/{project}/locations/{location}/namespaces/{namespace}`
  public var name: Swift.String = Swift.String()

  /// Output only. Google-generated UUID for this resource. This is unique across
  /// all namespace resources. If a namespace resource is deleted and another
  /// resource with the same name is created, it gets a different uid.
  public var uid: Swift.String = Swift.String()

  /// Output only. When the namespace was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. When the namespace was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. When the namespace was deleted.
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. State of the namespace resource.
  public var state: NamespaceLifecycleState? = nil

  /// Required. Scope associated with the namespace
  public var scope: Swift.String = Swift.String()

  /// Optional. Namespace-level cluster namespace labels. These labels are
  /// applied to the related namespace of the member clusters bound to the parent
  /// Scope. Scope-level labels (`namespace_labels` in the Fleet Scope
  /// resource) take precedence over Namespace-level labels if they share
  /// a key. Keys and values must be Kubernetes-conformant.
  public var namespaceLabels: [Swift.String: Swift.String] = [:]

  /// Optional. Labels for this Namespace.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `Namespace`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Namespace().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.Namespace"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
