// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ResourceOptions represent options for Kubernetes resource generation.
public struct ResourceOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The Connect agent version to use for connect_resources. Defaults
  /// to the latest GKE Connect version. The version must be a currently
  /// supported version, obsolete versions will be rejected.
  public var connectVersion: Swift.String = Swift.String()

  /// Optional. Use `apiextensions/v1beta1` instead of `apiextensions/v1` for
  /// CustomResourceDefinition resources.
  /// This option should be set for clusters with Kubernetes apiserver versions
  /// <1.16.
  public var v1Beta1Crd: Swift.Bool = Swift.Bool()

  /// Optional. Major and minor version of the Kubernetes cluster. This is only
  /// used to determine which version to use for the CustomResourceDefinition
  /// resources, `apiextensions/v1beta1` or`apiextensions/v1`.
  public var k8SVersion: Swift.String = Swift.String()

  /// Optional. Git version of the Kubernetes cluster. This is only used to gate
  /// the Connect Agent migration to svc.id.goog on GDC-SO 1.33.100 patch and
  /// above.
  public var k8SGitVersion: Swift.String = Swift.String()

  /// Initialize a new instance of `ResourceOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceOptions().with { $0.connectVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case connectVersion = "connectVersion"
    case v1Beta1Crd = "v1beta1Crd"
    case k8SVersion = "k8sVersion"
    case k8SGitVersion = "k8sGitVersion"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.connectVersion = try container.decode(Swift.String.self, forKey: .connectVersion)
    self.v1Beta1Crd = try container.decode(Swift.Bool.self, forKey: .v1Beta1Crd)
    self.k8SVersion = try container.decode(Swift.String.self, forKey: .k8SVersion)
    self.k8SGitVersion = try container.decode(Swift.String.self, forKey: .k8SGitVersion)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.connectVersion, forKey: .connectVersion)
    try container.encode(self.v1Beta1Crd, forKey: .v1Beta1Crd)
    try container.encode(self.k8SVersion, forKey: .k8SVersion)
    try container.encode(self.k8SGitVersion, forKey: .k8SGitVersion)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.gkehub.v1.ResourceOptions"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
