// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ResourceManifest represents a single Kubernetes resource to be applied to
/// the cluster.
public struct ResourceManifest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// YAML manifest of the resource.
  public var manifest: Swift.String = Swift.String()

  /// Whether the resource provided in the manifest is `cluster_scoped`.
  /// If unset, the manifest is assumed to be namespace scoped.
  ///
  /// This field is used for REST mapping when applying the resource in a
  /// cluster.
  public var clusterScoped: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ResourceManifest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceManifest().with { $0.manifest = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.v1.ResourceManifest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
